### ISSUE TITLE
Unable to build on EAS Cloud on v2.9.0, Cannot find module 'node:assert'

### ISSUE THREAD

**Issue by HishamOmran** [expo/eas-cli#1566]
### Build/Submit details page URL

No build URL to provide as it fails before reaching EAS Cloud

### Summary

After the latest update to v2.9.0, it seems like all builds fail when running the `eas-cli build` via NPX. 

Downgrading the version via `npx eas-cli@2.8.0 build -p all` seems to work which means something must be conflicting on `v2.9.0`

### Managed or bare?

Managed

### Environment

```
❯ npx expo-env-info
npx: installed 2 in 3.083s

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.6
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 14.17.5 - ~/.nvm/versions/node/v14.17.5/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v14.17.5/bin/yarn
      npm: 6.14.14 - ~/.nvm/versions/node/v14.17.5/bin/npm
      Watchman: 2022.10.03.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8609683
      Xcode: 14.0.1/14A400 - /usr/bin/xcodebuild
    npmPackages:
      babel-preset-expo: ~9.2.1 => 9.2.2 
      expo: ^47.0.0 => 47.0.7 
      react: 18.1.0 => 18.1.0 
      react-native: 0.70.5 => 0.70.5 
    npmGlobalPackages:
      eas-cli: 2.9.0
      expo-cli: 6.0.5
    Expo Workflow: managed
```

```
❯ npx expo-cli doctor    
✖ Dependency tree validation for expo-modules-autolinking failed. This validation is only available on Node 16+ / npm 8.
✖ Dependency tree validation for @expo/config-plugins failed. This validation is only available on Node 16+ / npm 8.
✖ Dependency tree validation for @expo/prebuild-config failed. This validation is only available on Node 16+ / npm 8.
✖ Dependency tree validation for @unimodules/core failed. This validation is only available on Node 16+ / npm 8.
✖ Dependency tree validation for @unimodules/react-native-adapter failed. This validation is only available on Node 16+ / npm 8.
✖ Dependency tree validation for react-native-unimodules failed. This validation is only available on Node 16+ / npm 8.
🎉 Didn't find any issues with the project!
```

### Error output

```
❯ npx eas-cli build -p all --profile release-review_app --non-interactive  
npx: installed 353 in 7.52s
 ›   ModuleLoadError: [MODULE_NOT_FOUND] require failed to load /Users/developer/.npm/_npx/90188/lib/node_modules/eas-cli/build/commands/build/index.js: Cannot find module 'node:assert'
 ›   Require stack:
 ›   - /Users/developer/.npm/_npx/90188/lib/node_modules/eas-cli/build/run/android/emulator.js
 ›   - /Users/developer/.npm/_npx/90188/lib/node_modules/eas-cli/build/run/android/run.js
 ›   - /Users/developer/.npm/_npx/90188/lib/node_modules/eas-cli/build/run/run.js
 ›   - /Users/developer/.npm/_npx/90188/lib/node_modules/eas-cli/build/build/runBuildAndSubmit.js
 ›   - /Users/developer/.npm/_npx/90188/lib/node_modules/eas-cli/build/commands/build/index.js
 ›   - /Users/developer/.npm/_npx/90188/lib/node_modules/eas-cli/node_modules/@oclif/core/lib/module-loader.js
 ›   - /Users/developer/.npm/_npx/90188/lib/node_modules/eas-cli/node_modules/@oclif/core/lib/config/plugin.js
 ›   - /Users/developer/.npm/_npx/90188/lib/node_modules/eas-cli/node_modules/@oclif/core/lib/config/config.js
 ›   - /Users/developer/.npm/_npx/90188/lib/node_modules/eas-cli/node_modules/@oclif/core/lib/config/index.js
 ›   - /Users/developer/.npm/_npx/90188/lib/node_modules/eas-cli/node_modules/@oclif/core/lib/command.js
 ›   - /Users/developer/.npm/_npx/90188/lib/node_modules/eas-cli/node_modules/@oclif/core/lib/index.js
 ›   - /Users/developer/.npm/_npx/90188/lib/node_modules/eas-cli/bin/run
 ›   Code: MODULE_NOT_FOUND
```

### Reproducible demo or steps to reproduce from a blank project

- `expo init example-app`
- Link app to project by updating `app.json`
- Running `npx eas-cli build -p all` results in the error above.

**Comment by szdziedzic** [comment]
Hi,

Thanks for creating this issue. I already merged and released the fix. It should work again for you in `eas-cli` version `3.0.0`. Sorry for the inconvenience.

**Comment by HishamOmran** [comment]
@szdziedzic Thanks for the update, all looks great now 👍 
Appreciate the support 🙏
